export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 100;
export const NON_CANCELLABLE_BOOKING_STATUSES = ['ACTIVE', 'COMPLETED', 'CANCELLED', 'DISPUTED'];
export const ACTIVE_BOOKING_STATUSES = ['PENDING', 'CONFIRMED', 'ACTIVE'];
