export const IDEMPOTENCY_WINDOW_HOURS = 24;
export const PLATFORM_COMMISSION_PERCENT = 5;
export const MINIMUM_PAYOUT_AMOUNT = 1000;
export const PAYMENT_METHODS = ['PAYHERE', 'STRIPE', 'EZCASH', 'WALLET'];
