import type { User, UserProfile } from '@/types/user.types'

// ============================================================================
// MOCK USERS - Use these to login and test the frontend
// ============================================================================
// Password for all mock users: "password123"
// ============================================================================

export const MOCK_USERS: (User & { password: string })[] = [
  {
    id: 'user-001',
    email: 'kasun@example.com',
    password: 'password123',
    name: 'Kasun Perera',
    phone: '+94 71 234 5678',
    avatar: null,
    kycStatus: 'approved',
    isVerified: true,
    role: 'user',
    rating: 4.8,
    totalReviews: 23,
    joinedAt: '2025-01-15T10:00:00Z',
    lastActive: new Date().toISOString(),
  },
  {
    id: 'user-002',
    email: 'nimal@example.com',
    password: 'password123',
    name: 'Nimal Silva',
    phone: '+94 77 456 7890',
    avatar: null,
    kycStatus: 'pending',
    isVerified: false,
    role: 'user',
    rating: 4.5,
    totalReviews: 8,
    joinedAt: '2025-03-20T10:00:00Z',
    lastActive: new Date().toISOString(),
  },
  {
    id: 'user-003',
    email: 'dilini@example.com',
    password: 'password123',
    name: 'Dilini Fernando',
    phone: '+94 76 789 0123',
    avatar: null,
    kycStatus: 'approved',
    isVerified: true,
    role: 'user',
    rating: 4.9,
    totalReviews: 41,
    joinedAt: '2024-11-05T10:00:00Z',
    lastActive: new Date().toISOString(),
  },
  {
    id: 'user-004',
    email: 'ruwan@example.com',
    password: 'password123',
    name: 'Ruwan Jayawardena',
    phone: '+94 70 123 4567',
    avatar: null,
    kycStatus: 'not_started',
    isVerified: false,
    role: 'user',
    rating: undefined,
    totalReviews: 0,
    joinedAt: '2026-05-28T10:00:00Z',
    lastActive: new Date().toISOString(),
  },
  {
    id: 'admin-001',
    email: 'admin@rentlk.com',
    password: 'password123',
    name: 'Admin User',
    phone: '+94 11 234 5678',
    avatar: null,
    kycStatus: 'approved',
    isVerified: true,
    role: 'admin',
    rating: undefined,
    totalReviews: 0,
    joinedAt: '2024-01-01T10:00:00Z',
    lastActive: new Date().toISOString(),
  },
]

// ============================================================================
// MOCK USER PROFILES (extended data)
// ============================================================================

export const MOCK_USER_PROFILES: Record<string, UserProfile> = {
  'user-001': {
    ...MOCK_USERS[0],
    bio: 'Passionate about cars and travel. I love exploring Sri Lanka by road!',
    address: '42 Galle Road, Colombo 03',
    city: 'Colombo',
    dateOfBirth: '1990-05-15',
    drivingLicenseNumber: 'B12345678',
    emergencyContact: {
      name: 'Amali Perera',
      phone: '+94 71 987 6543',
      relationship: 'Spouse',
    },
    badges: ['Super Host', 'Early Adopter', 'Verified Driver'],
    totalBookings: 12,
    totalListings: 3,
    totalEarnings: 125000,
    responseRate: 98,
    responseTime: '< 1 hour',
  },
  'user-002': {
    ...MOCK_USERS[1],
    bio: 'Weekend traveler. Looking for reliable vehicles for my trips.',
    address: '15 Kandy Road, Kadugannawa',
    city: 'Kandy',
    dateOfBirth: '1995-08-22',
    drivingLicenseNumber: 'B87654321',
    badges: ['Verified Driver'],
    totalBookings: 5,
    totalListings: 1,
    totalEarnings: 18000,
    responseRate: 85,
    responseTime: '< 3 hours',
  },
  'user-003': {
    ...MOCK_USERS[2],
    bio: 'Professional driver and vehicle owner. Top-rated host on the platform.',
    address: '88 Beach Road, Galle',
    city: 'Galle',
    dateOfBirth: '1988-12-10',
    drivingLicenseNumber: 'B11223344',
    emergencyContact: {
      name: 'Sunil Fernando',
      phone: '+94 76 111 2222',
      relationship: 'Brother',
    },
    badges: ['Super Host', 'Top Earner', 'Verified Driver', '50+ Bookings'],
    totalBookings: 3,
    totalListings: 5,
    totalEarnings: 485000,
    responseRate: 99,
    responseTime: '< 30 min',
  },
}

// ============================================================================
// MOCK VEHICLES
// ============================================================================

export const MOCK_VEHICLES = [
  {
    id: 'vehicle-001',
    ownerId: 'user-001',
    ownerName: 'Kasun Perera',
    title: 'Toyota Prius 2020 - Hybrid',
    type: 'car',
    make: 'Toyota',
    model: 'Prius',
    year: 2020,
    transmission: 'automatic',
    fuel: 'hybrid',
    seats: 5,
    dailyRate: 5500,
    city: 'Colombo',
    location: 'Colombo 03',
    images: [
      'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=500&fit=crop',
    ],
    features: ['ac', 'gps', 'bluetooth', 'usb', 'camera', 'cruise-control', 'abs', 'airbags'],
    rating: 4.9,
    totalReviews: 15,
    totalBookings: 15,
    isAvailable: true,
    status: 'active',
    description: 'Well-maintained Toyota Prius with excellent fuel efficiency. Perfect for city drives and long trips. Comes with GPS and full insurance.',
    earnings: 82500,
    createdAt: '2025-02-10T10:00:00Z',
  },
  {
    id: 'vehicle-002',
    ownerId: 'user-001',
    ownerName: 'Kasun Perera',
    title: 'Honda Civic 2019 - Sport',
    type: 'car',
    make: 'Honda',
    model: 'Civic',
    year: 2019,
    transmission: 'automatic',
    fuel: 'petrol',
    seats: 5,
    dailyRate: 4500,
    city: 'Colombo',
    location: 'Colombo 05',
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop',
    ],
    features: ['ac', 'bluetooth', 'usb', 'abs', 'airbags'],
    rating: 4.7,
    totalReviews: 8,
    totalBookings: 8,
    isAvailable: true,
    status: 'active',
    description: 'Sporty Honda Civic in excellent condition. Great for highway drives and weekend getaways.',
    earnings: 36000,
    createdAt: '2025-04-15T10:00:00Z',
  },
  {
    id: 'vehicle-003',
    ownerId: 'user-003',
    ownerName: 'Dilini Fernando',
    title: 'Toyota KDH Van 2021',
    type: 'van',
    make: 'Toyota',
    model: 'KDH',
    year: 2021,
    transmission: 'manual',
    fuel: 'diesel',
    seats: 12,
    dailyRate: 8000,
    city: 'Galle',
    location: 'Galle Town',
    images: [
      'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&h=500&fit=crop',
    ],
    features: ['ac', 'gps', 'abs'],
    rating: 4.8,
    totalReviews: 22,
    totalBookings: 30,
    isAvailable: true,
    status: 'active',
    description: 'Spacious Toyota KDH van perfect for family trips and group travel. Can accommodate 12 passengers comfortably.',
    earnings: 240000,
    createdAt: '2024-12-01T10:00:00Z',
  },
  {
    id: 'vehicle-004',
    ownerId: 'user-003',
    ownerName: 'Dilini Fernando',
    title: 'Suzuki Alto 2022 - Budget',
    type: 'car',
    make: 'Suzuki',
    model: 'Alto',
    year: 2022,
    transmission: 'manual',
    fuel: 'petrol',
    seats: 4,
    dailyRate: 2500,
    city: 'Galle',
    location: 'Unawatuna',
    images: [
      'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=800&h=500&fit=crop',
    ],
    features: ['ac', 'usb'],
    rating: 4.6,
    totalReviews: 18,
    totalBookings: 25,
    isAvailable: false,
    status: 'active',
    description: 'Budget-friendly Suzuki Alto. Great fuel economy, easy to park. Perfect for solo travelers or couples.',
    earnings: 62500,
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'vehicle-005',
    ownerId: 'user-003',
    ownerName: 'Dilini Fernando',
    title: 'Bajaj Pulsar NS200 - Motorcycle',
    type: 'motorcycle',
    make: 'Bajaj',
    model: 'Pulsar NS200',
    year: 2023,
    transmission: 'manual',
    fuel: 'petrol',
    seats: 2,
    dailyRate: 1500,
    city: 'Galle',
    location: 'Galle Fort',
    images: [
      'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=500&fit=crop',
    ],
    features: ['abs'],
    rating: 4.9,
    totalReviews: 10,
    totalBookings: 20,
    isAvailable: true,
    status: 'active',
    description: 'Powerful Bajaj Pulsar NS200 motorcycle. Great for exploring the southern coast. Helmet included.',
    earnings: 30000,
    createdAt: '2025-03-10T10:00:00Z',
  },
  {
    id: 'vehicle-006',
    ownerId: 'user-002',
    ownerName: 'Nimal Silva',
    title: 'Tuk-Tuk - City Explorer',
    type: 'tuk-tuk',
    make: 'Bajaj',
    model: 'RE',
    year: 2022,
    transmission: 'manual',
    fuel: 'petrol',
    seats: 3,
    dailyRate: 1200,
    city: 'Kandy',
    location: 'Kandy City Center',
    images: [
      'https://images.unsplash.com/photo-1581578017093-cd30fce4eeb7?w=800&h=500&fit=crop',
    ],
    features: [],
    rating: 4.5,
    totalReviews: 5,
    totalBookings: 12,
    isAvailable: true,
    status: 'active',
    description: 'Iconic Sri Lankan tuk-tuk experience! Perfect for short trips around Kandy. Fun and affordable.',
    earnings: 14400,
    createdAt: '2025-05-01T10:00:00Z',
  },
]

// ============================================================================
// MOCK BOOKINGS
// ============================================================================

export const MOCK_BOOKINGS = [
  {
    id: 'booking-001',
    vehicleId: 'vehicle-001',
    vehicleTitle: 'Toyota Prius 2020 - Hybrid',
    vehicleImage: 'https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&h=500&fit=crop',
    renterId: 'user-002',
    renterName: 'Nimal Silva',
    ownerId: 'user-001',
    ownerName: 'Kasun Perera',
    startDate: '2026-06-10',
    endDate: '2026-06-15',
    days: 5,
    dailyRate: 5500,
    subtotal: 27500,
    commission: 1375,
    total: 28875,
    status: 'confirmed',
    paymentStatus: 'completed',
    pickupLocation: 'Colombo 03',
    dropoffLocation: 'Colombo 03',
    addOns: [],
    createdAt: '2026-06-01T10:00:00Z',
  },
  {
    id: 'booking-002',
    vehicleId: 'vehicle-002',
    vehicleTitle: 'Honda Civic 2019 - Sport',
    vehicleImage: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&h=500&fit=crop',
    renterId: 'user-002',
    renterName: 'Nimal Silva',
    ownerId: 'user-001',
    ownerName: 'Kasun Perera',
    startDate: '2026-06-20',
    endDate: '2026-06-22',
    days: 2,
    dailyRate: 4500,
    subtotal: 9000,
    commission: 450,
    total: 9450,
    status: 'pending',
    paymentStatus: 'pending',
    pickupLocation: 'Colombo 05',
    dropoffLocation: 'Kandy',
    addOns: ['insurance'],
    createdAt: '2026-06-03T10:00:00Z',
  },
  {
    id: 'booking-003',
    vehicleId: 'vehicle-003',
    vehicleTitle: 'Toyota KDH Van 2021',
    vehicleImage: 'https://images.unsplash.com/photo-1559416523-140ddc3d238c?w=800&h=500&fit=crop',
    renterId: 'user-001',
    renterName: 'Kasun Perera',
    ownerId: 'user-003',
    ownerName: 'Dilini Fernando',
    startDate: '2026-05-25',
    endDate: '2026-05-28',
    days: 3,
    dailyRate: 8000,
    subtotal: 24000,
    commission: 1200,
    total: 25200,
    status: 'active',
    paymentStatus: 'completed',
    pickupLocation: 'Galle Town',
    dropoffLocation: 'Galle Town',
    addOns: ['driver', 'insurance'],
    createdAt: '2026-05-20T10:00:00Z',
  },
  {
    id: 'booking-004',
    vehicleId: 'vehicle-005',
    vehicleTitle: 'Bajaj Pulsar NS200 - Motorcycle',
    vehicleImage: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?w=800&h=500&fit=crop',
    renterId: 'user-001',
    renterName: 'Kasun Perera',
    ownerId: 'user-003',
    ownerName: 'Dilini Fernando',
    startDate: '2026-05-10',
    endDate: '2026-05-12',
    days: 2,
    dailyRate: 1500,
    subtotal: 3000,
    commission: 150,
    total: 3150,
    status: 'completed',
    paymentStatus: 'completed',
    pickupLocation: 'Galle Fort',
    dropoffLocation: 'Galle Fort',
    addOns: [],
    createdAt: '2026-05-05T10:00:00Z',
    review: {
      id: 'review-001',
      rating: 5,
      comment: 'Amazing motorcycle! Perfect for coastal rides. Dilini was very helpful.',
      createdAt: '2026-05-13T10:00:00Z',
    },
  },
]

// ============================================================================
// MOCK CONVERSATIONS & MESSAGES
// ============================================================================

export const MOCK_CONVERSATIONS = [
  {
    id: 'conv-001',
    participants: [
      { id: 'user-001', name: 'Kasun Perera' },
      { id: 'user-002', name: 'Nimal Silva' },
    ],
    vehicleId: 'vehicle-001',
    vehicleTitle: 'Toyota Prius 2020 - Hybrid',
    lastMessage: 'Is the vehicle available for June 10-15?',
    lastMessageAt: '2026-06-03T14:30:00Z',
    unreadCount: 2,
  },
  {
    id: 'conv-002',
    participants: [
      { id: 'user-001', name: 'Kasun Perera' },
      { id: 'user-003', name: 'Dilini Fernando' },
    ],
    vehicleId: 'vehicle-003',
    vehicleTitle: 'Toyota KDH Van 2021',
    lastMessage: 'Thank you! I will pick it up at 9am.',
    lastMessageAt: '2026-05-24T18:00:00Z',
    unreadCount: 0,
  },
  {
    id: 'conv-003',
    participants: [
      { id: 'user-001', name: 'Kasun Perera' },
      { id: 'user-003', name: 'Dilini Fernando' },
    ],
    vehicleId: 'vehicle-005',
    vehicleTitle: 'Bajaj Pulsar NS200 - Motorcycle',
    lastMessage: 'Great ride! Left a 5-star review.',
    lastMessageAt: '2026-05-13T10:00:00Z',
    unreadCount: 1,
  },
]

export const MOCK_MESSAGES: Record<string, Array<{
  id: string
  senderId: string
  senderName: string
  content: string
  createdAt: string
  isRead: boolean
}>> = {
  'conv-001': [
    {
      id: 'msg-001',
      senderId: 'user-002',
      senderName: 'Nimal Silva',
      content: 'Hi Kasun! I am interested in renting your Toyota Prius for a trip to Kandy.',
      createdAt: '2026-06-03T14:00:00Z',
      isRead: true,
    },
    {
      id: 'msg-002',
      senderId: 'user-001',
      senderName: 'Kasun Perera',
      content: 'Hi Nimal! Sure, the vehicle is available. What dates are you looking at?',
      createdAt: '2026-06-03T14:15:00Z',
      isRead: true,
    },
    {
      id: 'msg-003',
      senderId: 'user-002',
      senderName: 'Nimal Silva',
      content: 'Is the vehicle available for June 10-15?',
      createdAt: '2026-06-03T14:30:00Z',
      isRead: false,
    },
  ],
  'conv-002': [
    {
      id: 'msg-004',
      senderId: 'user-001',
      senderName: 'Kasun Perera',
      content: 'Hi Dilini, I booked your KDH van for the Galle trip. Can I pick it up early morning?',
      createdAt: '2026-05-24T17:00:00Z',
      isRead: true,
    },
    {
      id: 'msg-005',
      senderId: 'user-003',
      senderName: 'Dilini Fernando',
      content: 'Sure! You can pick it up from 7am onwards. I will have it fueled and ready.',
      createdAt: '2026-05-24T17:30:00Z',
      isRead: true,
    },
    {
      id: 'msg-006',
      senderId: 'user-001',
      senderName: 'Kasun Perera',
      content: 'Thank you! I will pick it up at 9am.',
      createdAt: '2026-05-24T18:00:00Z',
      isRead: true,
    },
  ],
}

// ============================================================================
// MOCK NOTIFICATIONS
// ============================================================================

export const MOCK_NOTIFICATIONS = [
  {
    id: 'notif-001',
    type: 'booking_request',
    title: 'New Booking Request',
    message: 'Nimal Silva wants to book your Honda Civic for June 20-22',
    isRead: false,
    createdAt: '2026-06-03T10:00:00Z',
    data: { bookingId: 'booking-002' },
  },
  {
    id: 'notif-002',
    type: 'message',
    title: 'New Message',
    message: 'Nimal Silva sent you a message about Toyota Prius',
    isRead: false,
    createdAt: '2026-06-03T14:30:00Z',
    data: { conversationId: 'conv-001' },
  },
  {
    id: 'notif-003',
    type: 'payment',
    title: 'Payment Received',
    message: 'You received LKR 28,875 for booking #booking-001',
    isRead: true,
    createdAt: '2026-06-01T10:30:00Z',
    data: { paymentId: 'pay-001' },
  },
  {
    id: 'notif-004',
    type: 'review',
    title: 'New Review',
    message: 'You received a 5-star review from a recent booking',
    isRead: true,
    createdAt: '2026-05-13T11:00:00Z',
    data: { reviewId: 'review-001' },
  },
  {
    id: 'notif-005',
    type: 'kyc',
    title: 'KYC Approved',
    message: 'Your KYC verification has been approved. You can now book and list vehicles!',
    isRead: true,
    createdAt: '2025-01-16T10:00:00Z',
    data: {},
  },
]

// ============================================================================
// MOCK REVIEWS
// ============================================================================

export const MOCK_REVIEWS = [
  {
    id: 'review-001',
    bookingId: 'booking-004',
    reviewerId: 'user-001',
    reviewerName: 'Kasun Perera',
    revieweeId: 'user-003',
    revieweeName: 'Dilini Fernando',
    vehicleId: 'vehicle-005',
    vehicleTitle: 'Bajaj Pulsar NS200',
    rating: 5,
    comment: 'Amazing motorcycle! Perfect for coastal rides. Dilini was very helpful and the bike was in great condition.',
    createdAt: '2026-05-13T10:00:00Z',
  },
  {
    id: 'review-002',
    bookingId: 'booking-003',
    reviewerId: 'user-002',
    reviewerName: 'Nimal Silva',
    revieweeId: 'user-001',
    revieweeName: 'Kasun Perera',
    vehicleId: 'vehicle-001',
    vehicleTitle: 'Toyota Prius 2020',
    rating: 5,
    comment: 'Excellent car, very fuel efficient. Kasun was responsive and easy to deal with.',
    createdAt: '2026-05-16T10:00:00Z',
  },
  {
    id: 'review-003',
    bookingId: 'booking-001',
    reviewerId: 'user-001',
    reviewerName: 'Kasun Perera',
    revieweeId: 'user-003',
    revieweeName: 'Dilini Fernando',
    vehicleId: 'vehicle-003',
    vehicleTitle: 'Toyota KDH Van',
    rating: 4,
    comment: 'Great van for our family trip. Spacious and comfortable. Would rent again!',
    createdAt: '2026-05-29T10:00:00Z',
  },
]

// ============================================================================
// MOCK WALLET
// ============================================================================

export const MOCK_WALLET = {
  userId: 'user-001',
  balance: 45000,
  pendingBalance: 9450,
  availableBalance: 35550,
  heldBalance: 0,
  isActive: true,
  transactions: [
    { id: 'tx-001', type: 'CREDIT', amount: 28875, description: 'Booking payment - Toyota Prius', createdAt: '2026-06-01T10:30:00Z' },
    { id: 'tx-002', type: 'CREDIT', amount: 3150, description: 'Booking payment - Bajaj Pulsar', createdAt: '2026-05-05T10:30:00Z' },
    { id: 'tx-003', type: 'DEBIT', amount: 25200, description: 'Booking payment - Toyota KDH Van', createdAt: '2026-05-20T10:30:00Z' },
    { id: 'tx-004', type: 'PAYOUT', amount: 50000, description: 'Payout to bank account', createdAt: '2026-05-15T10:30:00Z' },
    { id: 'tx-005', type: 'CREDIT', amount: 82500, description: 'Historical earnings', createdAt: '2025-12-01T10:30:00Z' },
  ],
}
